config/routes.rb
TaskManager::Application.routes.draw do
  root :to => "web/stories#index"

  scope :module => :web do
    resources :users, :only => [:new, :create]

    resource :session, :only => [:new, :create, :destroy]

    resources :stories do
      resources :comments, :only => [:create]
      member do
        put 'update_state'
      end
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :story
  attr_accessible :body, :commenter, :story_id
end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :name, :text, :sender_id, :reciver_id, :state

  belongs_to  :sender,  :class_name => "User"
  belongs_to  :reciver, :class_name  => "User"
  has_many :comments, :dependent => :destroy

  state_machine :initial => :new do
    event :start do
      transition :new => :started
    end

    event :finish do
      transition :started => :finished
    end

    event :accept do
      transition :finished => :accepted
    end

    event :reject do
      transition :finished => :rejected
    end

    event :restart do
      transition :rejected => :started
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :sender_stories

  has_secure_password

  has_many :sender_stories, :foreign_key => :sender_id, :class_name => "Story"
  has_many :reciver_stories, :foreign_key => :reciver_id, :class_name => "Story"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include AuthHelper

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html, :js

  def index
    @comments = Comment.scoped
  end

  def create
    @comment = Comment.new(params[:comment])

    unless  @comment.save
      redirect_to new_comment_path
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      sign_in(user)
      flash[:notice] = 'Logged in!'
      redirect_to root_url
    else
      flash.now.alert = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    sign_out
    flash[:notice] = 'Logged out!'
    redirect_to root_url
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  respond_to :html, :js
  before_filter :authenticate_user!

  def index
    @users = User.scoped
    @selected_reciver_id = 0
    if params[:search]
      @selected_reciver_id = params[:search][:reciver_id].to_i
      @selected_state = params[:search][:state].to_s
    end
    @stories = Story.search_by_reciver_id_and_state(@selected_reciver_id, @selected_state)
  end

  def show
    @story = Story.find(params[:id])
    @comment = @story.comments.new
  end

  def new
    @story = Story.new
    @users = User.scoped
  end

  def edit
    @story = Story.find(params[:id])
  end

  def create
    @user = current_user
    @story = @user.sender_stories.new(params[:story])

    if @story.save
      flash[:notice] = 'Story was created'
      redirect_to story_path(@story)
    else
      redirect_to new_story_path
    end
  end

  def update
    @story = Story.find(params[:id])

    if @story.update_attributes(params[:story])
      flash[:notice] = 'Story was updated'
      redirect_to story_path(@story)
    else
      render action: "edit"
    end
  end

  def update_state
    event = params[:event]
    @story = Story.find(params[:id])
    @story.fire_state_event(event)
    render layout: false
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    redirect_to stories_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = 'Signed up!'
      redirect_to root_url
    else
      render new_user_path
    end
  end

end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  include FlashHelper
end

app/controllers/web/comments_controller.rb
class Web::CommentsController < Web::ApplicationController
  respond_to :html, :js

  def create
    @story = Story.find(params[:story_id])
    @comment = @story.comments.create(params[:comment])

    if @comment.save
      flash_success
      respond_with @comment
    else
      flash_error
      redirect_to new_comment_path
    end
  end

end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController

  def new
    @type = UserSignInType.new
  end

  def create
    @type = UserSignInType.new(params[:user_sign_in_type])

    if @type.valid?
      user = @type.user
      flash_success
      sign_in(user)
      redirect_to params[:from] || root_path
    else
      flash_error
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/web/stories_controller.rb
class Web::StoriesController < Web::ApplicationController
  respond_to :html, :js
  before_filter :authenticate_user!

  def index
    @users = User.scoped
    @search = Story.ransack(params[:q])
    @stories = @search.result
    @search.build_sort if @search.sorts.empty?
  end

  def show
    @story = Story.find(params[:id])
  end

  def new
    @story = Story.new
    @users = User.scoped
  end

  def edit
    @story = Story.find(params[:id])
  end

  def create
    @user = current_user
    @story = @user.sender_stories.build(params[:story])

    if @story.save
      flash_success
      redirect_to story_path(@story)
    else
      flash_error
      render action: 'new'
    end
  end

  def update
    @story = Story.find(params[:id])

    if @story.update_attributes(params[:story])
      flash_success
      redirect_to story_path(@story)
    else
      flash_error
      render action: "edit"
    end
  end

  def update_state
    event = params[:event]
    @story = Story.find(params[:id])
    @story.fire_state_event(event)
    render layout: false
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    redirect_to stories_path
  end

end

app/controllers/web/users_controller.rb
class Web::UsersController < Web::ApplicationController

  def new
    @user = UserRegistrationType.new
  end

  def create
    @user = UserRegistrationType.new(params[:user_registration_type])
    if @user.save
      flash_success
      redirect_to root_url
    else
      flash_error
      render action: 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include AuthHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/web/application.html.haml
!!!
%html
  %head
    %title TaskManager
    = include_gon
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top.navbar-inverse
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'TASK MANAGER', root_path, :class => 'brand'
          .nav-collapse
            %ul.nav
              %li= link_to t('.stories'), stories_path
    .container
      .row
        .span8
          - flash.each do |name, msg|
            = content_tag :div, msg, :id => "flash_#{name}"
          = yield
        .span4
          .well
            - if signed_in?
              %p
                = t('.enter_as')
                %i
                  = current_user.email
              = link_to t('.sign_out'), session_path, :method => :delete, :class => 'btn btn-link'

app/views/stories/show.html.haml
%p
  %b Name:
  = @story.name
%p
  %b Text:
  = @story.text
%p
  %b Reciver:
  = @story.reciver_id
%p
  %b Sender:
  = @story.sender_id
%p
  %b State:
  = @story.state_name
%h3 Comments
#list_comments
  - @story.comments.each do |comment|
    - if comment.persisted?
      = render comment
#comment_form
  = render 'comments/form', story: @story, comment: @comment
= link_to 'Edit', edit_story_path(@story)
|
\#{link_to 'Back', stories_path}

app/views/web/comments/_comment.haml
%div
  %p
    %b
      = t('.commenter')
    = comment.commenter
  %p
    %b
      = t('.body')
    = comment.body

app/views/web/comments/_form.html.haml
= simple_form_for(comment, url: story_comments_path(story), :remote => true) do |f|
  = f.error_notification
  .form-inputs
    = f.input :commenter
    = f.input :body
  = f.button :submit

app/views/web/comments/create.js.haml
$("#list_comments").append("#{escape_javascript(render :partial => @comment)}");

app/views/web/stories/_form.html.haml
= simple_form_for(@story, :html => {:class => 'form-horisontal'}) do |f|
  - if @story.errors.any?
    #error_explanation
      %h2
        = pluralize(@story.errors.count, "error")
        = t('.error_message')
      %ul
        - @story.errors.full_messages.each do |msg|
          %li= msg
  = f.input :name
  = f.input :text
  = f.association :reciver, :label_method => lambda { |user| "#{user.email}" }
  = f.input :state do
    = f.select :state, Story.state_machine.states.map {|state| [state.human_name, state.name]}
  = f.button :submit

app/views/web/stories/_story.html.haml
%tr.story{id: story.id}
  %td= story.name
  %td= story.text
  %td= story.reciver_id
  %td= story.sender_id
  %td= story.human_state_name
  %td
    - story.state_events.each do |event|
      = link_to(Story.human_state_event_name(event), update_state_story_path(story, :event => event), :method => :put, :remote => true, :class => "btn")
  %td= link_to t('.edit'), edit_story_path(story)
  %td= link_to t('.show'), story_path(story)
  %td= link_to t('.destroy'), story, method: :delete, data: { confirm: t('.are_you_sure') }

app/views/web/stories/edit.html.haml
%h1 
  = t('.title')
= render 'form'
= link_to t('.show'), @story
|
= link_to t('.back'), stories_path

app/views/web/stories/index.html.haml
%table#list_stories
  %tr
    %th 
      = Story.human_attribute_name(:name)
    %th 
      = Story.human_attribute_name(:text)
    %th 
      = Story.human_attribute_name(:reciver)
    %th 
      = Story.human_attribute_name(:sender)
    %th 
      = Story.human_attribute_name(:state)

  = search_form_for @search do |f|
    .row
      .span3
        = f.label :state
        = f.select :state_eq, Story.state_machine.states.map {|state| [state.human_name, state.name] }, :include_blank => true
      .span3
        = f.label :email
        = f.select :reciver_email_eq, User.scoped.map { |user| user.email }, :include_blank => true
      .span2
        %br
        = f.submit

  - @stories.each do |story|
    = render story
%br/
= link_to t('.add_story'), new_story_path,  :class => "btn"

app/views/web/stories/new.html.haml
%h1 
  = t('.title')
= render 'form'
= link_to t('.back'), stories_path, class: 'btn btn-link'

app/views/web/stories/show.html.haml
%h1
  = t('.title')
%p
  %b Name:
  = @story.name
%p
  %b Text:
  = @story.text
%p
  %b Reciver:
  = @story.reciver_id
%p
  %b Sender:
  = @story.sender_id
%p
  %b State:
  = @story.state_name
%h3 
  = t('.comments')
#list_comments
  - @story.comments.each do |comment|
    = render comment
#comment_form
  = render 'web/comments/form', story: @story, comment: @story.comments.build

= link_to  t('.edit'), edit_story_path(@story)
|
= link_to t('.back'), stories_path

app/views/web/stories/update_state.html.haml
= render 'story', story: @story

app/views/web/users/new.html.haml
%h1 
  = t('.title')
= simple_form_for @user, url: users_path do |f|
  = f.input :email, placeholder: 'user@domain.com'
  = f.input :password
  = f.input :password_confirmation
  = f.button :submit, t('.create_user')